export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    loginCookie: '/auth/login-cookie',
    logoutCookie: '/auth/logout-cookie',
    meCookie: '/auth/me-cookie',
    logout: '/auth/logout',
    csrfCookie: '/sanctum/csrf-cookie',
  },
  client: {
    availableBalance: '/cliente/saldo-disponible',
    myData: '/cliente/mis-datos',
    password: '/cliente/password',
    resetNip: '/cliente/nip/reset',
    correctionRequest: '/cliente/solicitud-correccion',
  },
  loans: {
    base: '/prestamos',
    plans: '/prestamos/planes',
    byId: (id) => `/prestamos/${id}`,
    cancel: (id) => `/prestamos/${id}/cancelar`,
    abonoSpei: (id) => `/prestamos/${id}/abono-spei`,
    mercadoPagoPreference: (id) => `/prestamos/${id}/mercadopago/preference`,
    mercadoPagoConfirm: '/prestamos/mercadopago/confirm',
    mercadoPagoFeeQuote: '/prestamos/mercadopago/fee-quote',
    bankDetails: '/prestamos/datos-bancarios',
    avalToken: '/cliente/aval-token',
    generateAvalToken: '/cliente/aval-token/generate',
    validateAvalToken: '/prestamos/validate-aval-token',
    pendingAvalRequests: '/prestamos/avales/pendientes',
    respondAval: (id) => `/prestamos/${id}/aval-responder`,
    statement: (id = null) => (id && id !== 'ALL' ? `/prestamos/${id}/estado-cuenta` : '/prestamos/estado-cuenta'),
  },
  savings: {
    base: '/ahorros',
    plans: '/ahorros/planes',
    frequency: '/ahorros/frecuencia',
    byId: (id) => `/ahorros/${id}`,
    checkout: (id) => `/ahorros/${id}/stripe/checkout`,
    confirmCheckout: (id) => `/ahorros/${id}/stripe/confirm`,
    withdraw: (id) => `/ahorros/${id}/retirar`,
    transfer: (id) => `/ahorros/${id}/transferir`,
    payLoan: (id) => `/ahorros/${id}/abonar-prestamo`,
    changeFee: (id) => `/ahorros/${id}/cambiar-cuota`,
    cancelStripe: (id) => `/ahorros/${id}/cancelar-stripe`,
    movements: (id) => `/ahorros/${id}/movimientos`,
    statement: (id = null) => (id && id !== 'ALL' ? `/ahorros/${id}/estado-cuenta` : '/ahorros/estado-cuenta'),
    pause: (id) => `/ahorros/${id}/pausar`,
    resume: (id) => `/ahorros/${id}/reanudar`,
    voluntaryDeposit: (id) => `/ahorros/${id}/aportacion-voluntaria`,
    depositLimit: (id) => `/ahorros/${id}/limite-deposito`,
    codiQr: (id) => `/ahorros/${id}/codi-qr`,
    mercadoPagoPreference: (id) => `/ahorros/${id}/mercadopago/preference`,
    mercadoPagoConfirm: '/ahorros/mercadopago/confirm',
    bankDetails: '/ahorros/datos-bancarios',
  },
  investments: {
    base: '/inversiones',
    plans: '/inversiones/planes',
    byId: (id) => `/inversiones/${id}`,
    checkout: (id) => `/inversiones/${id}/stripe/checkout`,
    confirmCheckout: (id) => `/inversiones/${id}/stripe/confirm`,
    payWithBalance: (id) => `/inversiones/${id}/pay-saldo`,
    movements: (id) => `/inversiones/${id}/movimientos`,
    statement: (id = null) => (id && id !== 'ALL' ? `/inversiones/${id}/estado-cuenta` : '/inversiones/estado-cuenta'),
  },
  notifications: {
    base: '/notificaciones',
    markRead: (id) => `/notificaciones/${id}/leida`,
    markAllRead: '/notificaciones/marcar-todas',
  },
  deposits: {
    base: '/depositos',
    byId: (id) => `/depositos/${id}`,
  },
};
